kind: pipeline
name: default

steps:
- name: test
  image: java:openjdk-8
  enviroment:
  - GRADLE_USER_HOME=~/.gradle
  commands:
  - ./gradlew test
- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://chat.privacytools.io
    roomid: AgrJcbhHZhTJVmhPSi:privacytools.io
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
